### ISSUE TITLE
BUG: Error when open the "examine CT window"

### ISSUE THREAD

**Issue by choldgraf** [aestrivex/gselu#6]
Bug just started popping up - when I open a CT scan and select "Examine CT" I get the following error:

``` python
Traceback (most recent call last):
  File "/home/knight/holdgraf/anaconda/lib/python2.7/site-packages/pyface/ui/qt4/action/action_item.py", line 160, in _qt4_on_triggered
    self.controller.perform(action)
  File "/home/knight/holdgraf/anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_base.py", line 138, in perform
    self.ui.do_undoable( self._perform, action )
  File "/home/knight/holdgraf/anaconda/lib/python2.7/site-packages/traitsui/ui.py", line 715, in do_undoable
    action( *args, **kw )
  File "/home/knight/holdgraf/anaconda/lib/python2.7/site-packages/traitsui/qt4/ui_base.py", line 158, in _perform
    method()
  File "gselu.py", line 1845, in do_examine_ct
    pd = self.construct_panel2d()
AttributeError: 'iEEGCoregistrationFrame' object has no attribute 'construct_panel2d'
```

**Comment by aestrivex** [comment]
Sorry about that
